package com.github.f1rlefanz.cf_alarmfortimeoffice.hue.network

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertSame
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test
import org.mockito.kotlin.doThrow
import org.mockito.kotlin.mock
import org.mockito.kotlin.whenever
import java.security.KeyPairGenerator
import java.security.Principal
import java.security.PublicKey
import java.security.cert.CertificateException
import java.security.cert.CertificateExpiredException
import java.security.cert.X509Certificate
import javax.net.ssl.SSLSession
import javax.net.ssl.X509TrustManager

/**
 * Unit tests for [HueTrustManager] — the permissive local-IoT TLS trust model for Philips
 * Hue Bridges.
 *
 * The interesting (and security-relevant) code path is the **Hue-specific fallback** that
 * runs when the Android system trust store rejects a certificate. To reach it
 * deterministically we inject a fake system [X509TrustManager] via the `internal`
 * constructor: one that always throws forces every request onto the fallback, one that
 * always succeeds keeps everything on the system-trust path.
 *
 * Certificates are Mockito mocks of the abstract [X509Certificate] with only the members
 * the production code actually reads stubbed (`subjectDN`, `issuerDN`, `publicKey`,
 * `sigAlgName`, `checkValidity()`). Public keys are **real** keys generated by
 * [KeyPairGenerator] so the RSA-key-strength / EC branches in `validateCertificateStrength`
 * are exercised against genuine key material. [pinningStore] is passed as `null` so the
 * additive Layer-3 pinning is a no-op (it needs a real Android Context/SharedPreferences).
 */
class HueTrustManagerTest {

    // --- Real key material (generated once; RSA-2048 generation is comparatively slow) ---

    private val rsa2048: PublicKey by lazy { rsaKey(2048) }
    private val rsa1024: PublicKey by lazy { rsaKey(1024) }
    private val ecKey: PublicKey by lazy {
        KeyPairGenerator.getInstance("EC").apply { initialize(256) }.generateKeyPair().public
    }

    private fun rsaKey(bits: Int): PublicKey =
        KeyPairGenerator.getInstance("RSA").apply { initialize(bits) }.generateKeyPair().public

    // --- Fake system trust managers -------------------------------------------------------

    /** Rejects everything → drives all validation onto the Hue-specific fallback path. */
    private val rejectingSystemTm = object : X509TrustManager {
        override fun checkClientTrusted(chain: Array<X509Certificate>, authType: String) =
            throw CertificateException("system trust store: reject")

        override fun checkServerTrusted(chain: Array<X509Certificate>, authType: String) =
            throw CertificateException("system trust store: reject")

        override fun getAcceptedIssuers(): Array<X509Certificate> = emptyArray()
    }

    /** Accepts everything → keeps validation on the system-trust path (fallback untouched). */
    private val acceptingSystemTm = object : X509TrustManager {
        override fun checkClientTrusted(chain: Array<X509Certificate>, authType: String) = Unit
        override fun checkServerTrusted(chain: Array<X509Certificate>, authType: String) = Unit
        override fun getAcceptedIssuers(): Array<X509Certificate> = emptyArray()
    }

    // --- Certificate helpers --------------------------------------------------------------

    private fun dnPrincipal(dn: String): Principal = object : Principal {
        override fun getName(): String = dn
        override fun toString(): String = dn
    }

    private fun fakeCert(
        subject: String,
        issuer: String = subject,
        key: PublicKey? = rsa2048,
        sigAlg: String = "SHA256withRSA",
        expired: Boolean = false,
    ): X509Certificate {
        val cert = mock<X509Certificate>()
        whenever(cert.subjectDN).thenReturn(dnPrincipal(subject))
        whenever(cert.issuerDN).thenReturn(dnPrincipal(issuer))
        whenever(cert.publicKey).thenReturn(key)
        whenever(cert.sigAlgName).thenReturn(sigAlg)
        if (expired) {
            doThrow(CertificateExpiredException("expired")).whenever(cert).checkValidity()
        }
        return cert
    }

    // --- checkServerTrusted: system-trust path -------------------------------------------

    @Test
    fun `checkServerTrusted accepts anything the system trust store accepts`() {
        val tm = HueTrustManager(acceptingSystemTm, null)
        // A cert that would fail the Hue fallback (non-Hue, unrelated issuer) must still be
        // accepted because the system trust store validated it first.
        val cert = fakeCert(subject = "CN=example.com", issuer = "CN=Public Root CA")

        tm.checkServerTrusted(arrayOf(cert), "RSA") // must not throw
    }

    // --- checkServerTrusted: Hue fallback, accept cases ----------------------------------

    @Test
    fun `checkServerTrusted accepts a valid Philips Hue bridge certificate via fallback`() {
        val tm = HueTrustManager(rejectingSystemTm, null)
        val cert = fakeCert(subject = "CN=Philips Hue, O=Signify", key = rsa2048)

        tm.checkServerTrusted(arrayOf(cert), "RSA") // must not throw
    }

    @Test
    fun `checkServerTrusted accepts a self-signed local bridge certificate with an EC key`() {
        val tm = HueTrustManager(rejectingSystemTm, null)
        // No Hue keyword, no bridge-id hex run → only the self-signed branch (subject==issuer)
        // can accept it. EC key exercises the ECDSA strength branch.
        val cert = fakeCert(subject = "CN=192.168.1.50", issuer = "CN=192.168.1.50", key = ecKey)

        tm.checkServerTrusted(arrayOf(cert), "ECDHE_ECDSA") // must not throw
    }

    // --- checkServerTrusted: Hue fallback, reject cases ----------------------------------

    @Test
    fun `checkServerTrusted rejects a non-Hue certificate that fails the fallback patterns`() {
        val tm = HueTrustManager(rejectingSystemTm, null)
        val cert = fakeCert(
            subject = "CN=evil.example.com, O=EvilCorp",
            issuer = "CN=EvilCorp Root, O=EvilCorp", // not self-signed, no Hue markers
            key = rsa2048,
        )

        assertThrows(CertificateException::class.java) {
            tm.checkServerTrusted(arrayOf(cert), "RSA")
        }
    }

    @Test
    fun `checkServerTrusted rejects an expired certificate`() {
        val tm = HueTrustManager(rejectingSystemTm, null)
        val cert = fakeCert(subject = "CN=Philips Hue, O=Signify", expired = true)

        assertThrows(CertificateException::class.java) {
            tm.checkServerTrusted(arrayOf(cert), "RSA")
        }
    }

    @Test
    fun `checkServerTrusted rejects an empty certificate chain`() {
        val tm = HueTrustManager(rejectingSystemTm, null)

        assertThrows(CertificateException::class.java) {
            tm.checkServerTrusted(emptyArray(), "RSA")
        }
    }

    @Test
    fun `checkServerTrusted rejects a Hue certificate with an under-strength RSA key`() {
        val tm = HueTrustManager(rejectingSystemTm, null)
        val cert = fakeCert(subject = "CN=Philips Hue, O=Signify", key = rsa1024)

        assertThrows(CertificateException::class.java) {
            tm.checkServerTrusted(arrayOf(cert), "RSA")
        }
    }

    // --- checkClientTrusted --------------------------------------------------------------

    @Test
    fun `checkClientTrusted accepts a valid Hue certificate via fallback`() {
        val tm = HueTrustManager(rejectingSystemTm, null)
        val cert = fakeCert(subject = "CN=Hue Bridge, O=Signify", key = rsa2048)

        tm.checkClientTrusted(arrayOf(cert), "RSA") // must not throw
    }

    // --- getAcceptedIssuers --------------------------------------------------------------

    @Test
    fun `getAcceptedIssuers passes through the system trust store issuers`() {
        val issuer = mock<X509Certificate>()
        val systemTm = object : X509TrustManager {
            override fun checkClientTrusted(chain: Array<X509Certificate>, authType: String) = Unit
            override fun checkServerTrusted(chain: Array<X509Certificate>, authType: String) = Unit
            override fun getAcceptedIssuers(): Array<X509Certificate> = arrayOf(issuer)
        }

        val result = HueTrustManager(systemTm, null).acceptedIssuers

        assertEquals(1, result.size)
        assertSame(issuer, result[0])
    }

    @Test
    fun `getAcceptedIssuers returns empty array when the system trust store throws`() {
        val systemTm = object : X509TrustManager {
            override fun checkClientTrusted(chain: Array<X509Certificate>, authType: String) = Unit
            override fun checkServerTrusted(chain: Array<X509Certificate>, authType: String) = Unit
            override fun getAcceptedIssuers(): Array<X509Certificate> =
                throw IllegalStateException("boom")
        }

        val result = HueTrustManager(systemTm, null).acceptedIssuers

        assertEquals(0, result.size)
    }

    // --- extractBridgeIdFromCertificate (companion, internal) ----------------------------

    @Test
    fun `extractBridgeIdFromCertificate pulls the hex bridge id out of the CN`() {
        val cert = fakeCert(subject = "CN=001788fffe112233, O=Philips Hue")

        assertEquals(
            "001788fffe112233",
            HueTrustManager.extractBridgeIdFromCertificate(cert),
        )
    }

    @Test
    fun `extractBridgeIdFromCertificate lowercases the extracted id`() {
        val cert = fakeCert(subject = "CN=00AABBCCDDEE, O=Philips Hue")

        assertEquals("00aabbccddee", HueTrustManager.extractBridgeIdFromCertificate(cert))
    }

    @Test
    fun `extractBridgeIdFromCertificate returns null when the CN has no hex token`() {
        val cert = fakeCert(subject = "CN=Wohnzimmer, O=Philips Hue")

        assertNull(HueTrustManager.extractBridgeIdFromCertificate(cert))
    }

    @Test
    fun `extractBridgeIdFromCertificate returns null when there is no CN`() {
        val cert = fakeCert(subject = "O=Philips, OU=Hue")

        assertNull(HueTrustManager.extractBridgeIdFromCertificate(cert))
    }

    // --- Hostname verifier (private-network + valid session) -----------------------------

    private fun validSession(): SSLSession = mock<SSLSession>().also {
        whenever(it.isValid).thenReturn(true)
        whenever(it.cipherSuite).thenReturn("TLS_AES_128_GCM_SHA256")
    }

    @Test
    fun `hostname verifier accepts private-network addresses with a valid session`() {
        val verifier = HueTrustManager.createHostnameVerifier()
        val session = validSession()

        assertTrue(verifier.verify("192.168.1.10", session))
        assertTrue(verifier.verify("10.0.0.5", session))
        assertTrue(verifier.verify("172.16.0.1", session))
        assertTrue(verifier.verify("169.254.1.1", session))
    }

    @Test
    fun `hostname verifier rejects public addresses`() {
        val verifier = HueTrustManager.createHostnameVerifier()

        // Public / out-of-range addresses are rejected before the session is even consulted.
        assertFalse(verifier.verify("8.8.8.8", mock<SSLSession>()))
        assertFalse(verifier.verify("172.32.0.1", mock<SSLSession>()))
    }

    @Test
    fun `hostname verifier rejects a private address when the TLS session is invalid`() {
        val verifier = HueTrustManager.createHostnameVerifier()
        val session = mock<SSLSession>().also {
            whenever(it.isValid).thenReturn(false)
            whenever(it.cipherSuite).thenReturn("TLS_AES_128_GCM_SHA256")
        }

        assertFalse(verifier.verify("192.168.1.10", session))
    }

    @Test
    fun `hostname verifier rejects suspicious hostname patterns`() {
        val verifier = HueTrustManager.createHostnameVerifier()

        assertFalse(verifier.verify("192.168..1", mock<SSLSession>()))
        assertFalse(verifier.verify("https://192.168.1.10", mock<SSLSession>()))
    }
}
